# Generated by Django 2.0.7 on 2018-08-15 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('uid', models.CharField(default=uuid.uuid4, max_length=40, unique=True)),
            ],
        ),
    ]
