# Generated by Django 2.0.7 on 2018-08-08 05:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.CharField(default=uuid.UUID('1f0eed86-d727-46ea-8ebe-38959e5d758e'), max_length=40)),
            ],
        ),
    ]
