# Generated by Django 2.0.7 on 2018-08-09 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180808_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('eb85ef5b-9648-4b54-b914-7ab977a45a7a'), max_length=40),
        ),
    ]
