# Generated by Django 2.0.7 on 2018-08-09 15:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180809_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('0fbddbd9-b3ed-4a52-a39a-5e28141d1388'), max_length=40),
        ),
    ]
