# Generated by Django 2.0.7 on 2018-08-13 07:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180809_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('c4c05214-01a0-4cb0-9a37-dd62fb7b2752'), max_length=40),
        ),
    ]
