# Generated by Django 2.0.7 on 2018-08-13 07:48

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180813_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('094aac89-a43d-458a-8089-b957b16da33b'), max_length=40),
        ),
    ]
