# Generated by Django 2.0.7 on 2018-08-13 09:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180813_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='uid',
            field=models.CharField(default=uuid.UUID('ef1a0cac-b69b-4dd4-98ac-fa77a72a3823'), max_length=40, unique=True),
        ),
    ]
