# Generated by Django 2.0.7 on 2018-08-08 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_item_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ('id',)},
        ),
    ]
